=== VladTsarikov/Equipment/resources/EquipmentsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.it-academy.by/EquipmentsSchema" 
	    xmlns:tns="http://www.it-academy.by/EquipmentsSchema" 
		elementFormDefault="qualified">
<xs:element name = "equipments">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="equipment">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string"/>
						<xs:element name="price" type="xs:double"/>
						<xs:element name="gender" type="xs:string"/>
						<xs:element name="type" type="xs:string"/>
						<xs:element name="kindOfFrame" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="id" type="xs:int"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="equipment">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string"/>
						<xs:element name="price" type="xs:double"/>
						<xs:element name="gender" type="xs:string"/>
						<xs:element name="size" type="xs:int"/>
						<xs:element name="diameterOfWheels" type="xs:int"/>
					</xs:sequence>
					<xs:attribute name="id" type="xs:int"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="equipment">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string"/>
						<xs:element name="price" type="xs:double"/>
						<xs:element name="gender" type="xs:string"/>
						<xs:element name="size" type="xs:int"/>
					</xs:sequence>
					<xs:attribute name="id" type="xs:int"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="equipment">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string"/>
						<xs:element name="price" type="xs:double"/>
						<xs:element name="gender" type="xs:string"/>
						<xs:element name="size" type="xs:int"/>
					</xs:sequence>
					<xs:attribute name="id" type="xs:int"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== VladTsarikov/Equipment/resources/Equipments.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipments xmlns="http://www.it-academy.by/EquipmentsSchema"  
	   		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	   		xsi:schemaLocation = "http://www.it-academy.by/EquipmentsSchema EquipmentsSchema.xsd">
	<equipment id="1">
		<title>Bicycle-LTD</title>
		<price>8</price>
		<gender>Universal</gender>
		<type>Mountain bike</type>
		<kindOfFrame>Aluminum</kindOfFrame>
	</equipment>
	<equipment id="2">
		<title>Roller-Relmax</title>
		<price>7</price>
		<gender>Male</gender>
		<size>42</size>
		<diameterOfWheels>72</diameterOfWheels>
	</equipment>
	<equipment id="3">
		<title>Skate-Tukzar</title>
		<price>4</price>
		<gender>Female</gender>
		<size>38</size>
	</equipment>
	<equipment id="4">
		<title>Skiing-Monster</title>
		<price>4</price>
		<gender>Universal</gender>
		<size>170</size>
	</equipment>
</equipments>
